const portais = {
    "INSS": "https://atendimento.inss.gov.br/",
    "Juizado Especial Cível": "",
    "Juizado Especial da Fazenda Pública": "",
    "Juizado Especial Federal": "",
    "Justiça Federal 3ª Região": "",
    "Justiça Federal da 1ª Região": "",
    "Justiça Federal de Alagoas": "",
    "Justiça Federal de Goiás": "",
    "Justiça Federal do Espírito Santo": "https://eproc.jfes.jus.br/eproc/",
    "Justiça Federal de Sergipe": "https://pje1g.trf5.jus.br/pje/login.seam",
    "Superior Tribunal de Justiça": "https://cpe.web.stj.jus.br/",
    "Supremo Tribunal Federal": "https://portal.stf.jus.br/",
    "Tribunal de Justiça do Acre": "https://esaj.tjac.jus.br/esaj/portal.do?servico=740000",
    "Tribunal de Justiça de Alagoas": "https://www2.tjal.jus.br/esaj/portal.do?servico=820000",
    "Tribunal de Justiça do Amapá": "https://pje.tjap.jus.br/1g/login.seam",
    "Tribunal de Justiça do Amazonas": "https://projudi.tjam.jus.br/projudi/",
    "Tribunal de Justiça da Bahia": "https://pje.tjba.jus.br/pje/login.seam",
    "Tribunal de Justiça do Ceará": "https://pje.tjce.jus.br/pje1grau/login.seam",
    "Tribunal de Justiça do Espírito Santo": "https://pje.tjes.jus.br/pje/login.seam",
    "Tribunal de Justiça de Goiás": "https://projudi.tjgo.jus.br/",
    "Tribunal de Justiça do Maranhão": "https://pje.tjma.jus.br/pje/login.seam",
    "Tribunal de Justiça do Mato Grosso": "https://pje.tjmt.jus.br/pje/login.seam",
    "Tribunal de Justiça de Minas Gerais": "https://pje.tjmg.jus.br/pje/login.seam",
    "Tribunal de Justiça do Pará": "https://pje.tjpa.jus.br/pje/login.seam",
    "Tribunal de Justiça da Paraíba": "https://pje.tjpb.jus.br/pje/login.seam",
    "Tribunal de Justiça do Paraná": "https://projudi.tjpr.jus.br/projudi//",
    "Tribunal de Justiça de Pernambuco": "https://pje.cloud.tjpe.jus.br/1g/login.seam",
    "Tribunal de Justiça do Piauí": "https://pje.tjpi.jus.br/1g/login.seam",
    "Tribunal de Justiça de Rondônia": "https://pjepg.tjro.jus.br/login.seam",
    "Tribunal de Justiça do Rio Grande do Norte": "https://pje1g.tjrn.jus.br/pje/login.seam",
    "Tribunal de Justiça do Rio Grande do Sul": "https://ppe.tjrs.jus.br/ppe/signin",
    "Tribunal de Justiça do Rio de Janeiro": "https://tjrj.pje.jus.br/1g/login.seam",
    "Tribunal de Justiça de Roraima": "https://projudi.tjrr.jus.br/projudi/",
    "Tribunal de Justiça de São Paulo": "https://esaj.tjsp.jus.br/esaj/portal.do?servico=190090",
    "Tribunal de Justiça de Santa Catarina": "https://eproc1g.tjsc.jus.br/eproc/index.php",
    "Tribunal de Justiça de Sergipe": "https://www.tjse.jus.br/portaldoadvogado/",
    "Tribunal de Justiça do Tocantins": "https://eproc1.tjto.jus.br/eprocV2_prod_1grau/",
    "Tribunal de Justiça do Distrito Federal": "https://pje.tjdft.jus.br/pje/login.seam",
    "Tribunal Regional do Trabalho 1º": "https://pje.trt1.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 2º": "https://pje.trt2.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 3º": "https://pje.trt3.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 4º": "https://pje.trt4.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 5º": "https://pje.trt5.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 6º": "https://pje.trt6.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 7º": "https://pje.trt7.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 8º": "https://pje.trt8.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 9º": "https://pje.trt9.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 10º": "https://pje.trt10.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 11º": "https://pje.trt11.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 12º": "https://pje.trt12.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 13º": "https://pje.trt13.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 14º": "https://pje.trt14.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 15º": "https://pje.trt15.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 16º": "https://pje.trt16.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 17º": "https://pje.trt17.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 18º": "https://pje.trt18.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 19º": "https://pje.trt19.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 20º": "https://pje.trt20.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 21º": "https://pje.trt21.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 22º": "https://pje.trt22.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 23º": "https://pje.trt23.jus.br/primeirograu/login.seam",
    "Tribunal Regional do Trabalho 24º": "https://pje.trt24.jus.br/primeirograu/login.seam",
    "Tribunal Regional Federal da 1ª Região": "https://pje1g.trf1.jus.br/pje/login.seam",
    "Tribunal Regional Federal da 2ª Região": "https://eproc.trf2.jus.br/eproc/",
    "Tribunal Regional Federal da 3ª Região": "https://pje1g.trf3.jus.br/pje/login.seam",
    "Tribunal Regional Federal da 4ª Região": "https://pje1g.trf1.jus.br/pje/login.seam",
    "Tribunal Regional Federal da 5ª Região": "https://pje.jfse.jus.br/pje/login.seam",
    "Tribunal Regional Federal da 6ª Região": "https://pje.jfse.jus.br/pje/login.seam",
    "Tribunal Superior do Trabalho": "https://pje.tst.jus.br/tst/login.seam",
    "Turma Nacional de Uniformização": "https://www2.cjf.jus.br/pje/login.seam",
    "Turma Recursal dos JEC's": "",
    "Turma Recursal dos JEF's": "",
    "Turma Regional de Uniformização": "",
    "Vara de Ações Previdenciárias do DF": "https://pje.tjdft.jus.br/pje/login.seam"
}

