const ADM = [
    {
        id: 219,
        nome: "ARTHUR PORTO ROSENDO",
        nomeTLC: "ARTHUR",
        interiores: [],
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 256,
        nome: "CHRISTYAN RANGELL SILVA DAMASCENO XAVIER",
        nomeTLC: "CHRISTYAN",
        interiores: ["ESTANCIA", "TOBIAS BARRETO"],
        assignments: [assignments.contatar.geral],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 234,
        nome: "DAVI ALVES DOS SANTOS",
        nomeTLC: "DAVI",
        interiores: [],
        assignments: [assignments.contatar.BSB],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 204,
        nome: "DIEGO DOS SANTOS SILVA",
        nomeTLC: "DIEGO SANTOS",
        interiores: [],
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 238,
        nome: "ERICK RODRIGUES DE JEUS",
        nomeTLC: "ERICK",
        interiores: [],
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 263,
        nome: "GUILHERME CAUAN MATOS SILVA",
        nomeTLC: "GUILHERME",
        interiores: [],
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 205,
        nome: "HELTON FRADES BRABEC SOUZA",
        nomeTLC: "HELTON",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 239,
        nome: "ISAC CRUZ SANTOS",
        nomeTLC: "ISAC",
        interiores: [],
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 241,
        nome: "JEFERSON ALMEIDA SANTOS",
        nomeTLC: "JEFERSON",
        interiores: ["CARMOPOLIS", "PEDRINHAS"],
        assignments: [assignments.contatar.geral],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 197,
        nome: "JHONATHAN DA FONSECA ALMEIDA FLOR",
        nomeTLC: "JHONATHAN FONSECA",
        interiores: [],
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 247,
        nome: "JHONATAN NASCIMENTO TAVARES",
        nomeTLC: "JHONATHAN NASCIMENTO",
        assignments: [],
        interiores: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 51,
        nome: "JULIANO OLIVEIRA DE SOUZA",
        nomeTLC: "JULIANO",
        interiores: [],
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 221,
        nome: "LEONARDO TEIXEIRA SANTOS SILVA",
        nomeTLC: "LEONARDO",
        interiores: ["LOTEAMENTO JEOVA", "SANTA ROSA DE LIMA", "UMBAUBA"],
        assignments: [assignments.contatar.geral],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 199,
        nome: "LUCAS NATHAN NOGUEIRA DA SILVA",
        nomeTLC: "LUCAS",
        interiores: [],
        assignments: [assignments.contatar.geral],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 201,
        nome: "MARCO AURELIO LEITE GOMES",
        nomeTLC: "MARCO AURELIO",
        interiores: [],
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 231,
        nome: "MARIA LUANNA DE LIMA SOUZA",
        nomeTLC: "M. LUANNA",
        interiores: [],
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 223,
        nome: "MATHEUS CAMPELO DA SILVA",
        nomeTLC: "MATHEUS CAMPELO",
        interiores: [],
        assignments: [assignments.contatar.BSB],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 198,
        nome: "MURILLO VICTOR SANTOS ROCHA",
        nomeTLC: "MURILLO",
        interiores: [],
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 22,
        nome: "SANDOVAL FILHO CORREIA LIMA FILHO",
        nomeTLC: "SANDOVAL",
        interiores: [],
        assignments: [assignments.contatar.estancia],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 222,
        nome: "STEFANNY MORAIS DO NASCIMENTO",
        nomeTLC: "STEFANNY",
        interiores: [],
        assignments: [assignments.contatar.BSB],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 217,
        nome: "THIAGO SANTOS SANTANA",
        nomeTLC: "THIAGO",
        interiores: ["CAPELA", "JAPARATUBA", "CONDE/BA"],
        assignments: [assignments.contatar.geral],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 161,
        nome: "YURI DIAS PEREIRA",
        nomeTLC: "YURI",
        interiores: [],
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
]
const SAC = [
    {
        id: 259,
        nome: "ANDRE LUCAS SANTOS DA CRUZ",
        nomeTLC: "ANDRE LUCAS",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 233,
        nome: "EMILLY STHEFANE FERREIRA DOS SANTOS PEREIRA",
        nomeTLC: "EMILLY",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 225,
        nome: "ERINALDO FARO SANTOS",
        nomeTLC: "ERINALDO",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 139,
        nome: "FLAVIO LUCAS LIMA SOUZA",
        nomeTLC: "FLAVIO",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 213,
        nome: "HELLEN VITORIA ROCHA SILVA SANTOS",
        nomeTLC: "HELLEN",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 258,
        nome: "ICARO RODRIGO DOS SANTOS SILVA",
        nomeTLC: "ICARO RODRIGO",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 262,
        nome: "PATRICK DE OLIVEIRA COSTA",
        nomeTLC: "PATRICK",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 203,
        nome: "RENATA DE JESUS SANTOS",
        nomeTLC: "RENATA",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 245,
        nome: "SAULO LIMA ALVES DOS SANTOS",
        nomeTLC: "SAULO LIMA",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 232,
        nome: "SARA CRISTINA TELES LOIOLA",
        nomeTLC: "SARA CRISTINA",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 153,
        nome: "TRICYA MATEUS ROLEMBERG",
        nomeTLC: "TRICYA",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
]
const FINANCEIRO = [
    {
        id: 14,
        nome: "ALINE RIBEIRO",
        nomeTLC: "ALINE",
        interiores: null,
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 216,
        nome: "CAMILA TOJAL MACHADO SANTOS",
        nomeTLC: "CAMILA",
        interiores: null,
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 226,
        nome: "CARLOS FERNANDES PEREIRA DA SILVA",
        nomeTLC: "CARLOS FERNANDES",
        interiores: null,
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 11,
        nome: "LUCIANA DOS SANTOS ARAUJO",
        nomeTLC: "LUCIANA ARAUJO",
        interiores: null,
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 127,
        nome: "LUCIANA LIMA REZENDE",
        nomeTLC: "LUCIANA LIMA",
        interiores: null,
        assignments: [assignments.rpv],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 148,
        nome: "OVERLANDIA SANTOS MELO",
        nomeTLC: "OVERLANDIA",
        interiores: null,
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 207,
        nome: "SHEYLA SANTANA SANTOS",
        nomeTLC: "SHEYLA",
        interiores: null,
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 120,
        nome: "VICTOR MENDES DOS SANTOS",
        nomeTLC: "VICTOR",
        interiores: null,
        assignments: [assignments.alvara],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
]
const INSS = [
    {
        id: 235,
        nome: "ANDRÉ LEVY BATISTA DA SILVA",
        nomeTLC: "ANDRÉ",
        assignments: [assignments.inssDigital.prorrogacao],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 240,
        nome: "BRUNO PEREIRA LIMA VASCONCELOS",
        nomeTLC: "BRUNO",
        assignments: [assignments.inssDigital.prorrogacao],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 132,
        nome: "DANIEL CABRAL PEREIRA SANTOS",
        nomeTLC: "DANIEL",
        assignments: [assignments.inssDigital.prorrogacao, assignments.inssDigital.exigencia],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 115,
        nome: "GABRIEL FRANÇA VITAL",
        nomeTLC: "GABRIEL FRANÇA",
        assignments: [assignments.inssDigital.prorrogacao, assignments.inssDigital.exigencia],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 212,
        nome: "LUIZ CARLOS LOPES DOS SANTOS",
        nomeTLC: "LUIZ CARLOS",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 162,
        nome: "MIQUEAS CAMPOS DA SILVA",
        nomeTLC: "MIQUEAS",
        assignments: [assignments.inssDigital.exigencia],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 24,
        nome: "SILVANIA PINHEIRO DE LEMOS",
        nomeTLC: "SILVANIA",
        assignments: [assignments.inssDigital.exigencia],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
]
const PREVIDENCIARIO = [
    {
        id: 134,
        nome: "ANA CAROLINA SOARES DE MELO",
        nomeTLC: "ANA",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 251,
        nome: "ARTHUR PISISTRATO DE AMORIM REBELO",
        nomeTLC: "ARTHUR PISISTRATO",
        diasViagem: [],
        contagem: 0,
        tarefas: 0
    },
    {
        id: 1,
        nome: "DIEGO MELO SOBRINHO",
        nomeTLC: "DIEGO",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 192,
        nome: "EDUARDO PAIXÃO ROCHA SOBRINHO",
        nomeTLC: "EDUARDO",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 244,
        nome: "ELTON SILVA HONORATO",
        nomeTLC: "ELTON",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 2,
        nome: "FABIO RIBEIRO",
        nomeTLC: "FABIO",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 252,
        nome: "JOÃO VITOR FARIAS DOS SANTOS",
        nomeTLC: "JOÃO VITOR",
        diasViagem: [],
        contagem: 0,
        tarefas: 0
    },
    {
        id: 93,
        nome: "KEVEN FARO DE CARVALHO",
        nomeTLC: "KEVEN",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 28,
        nome: "MARCUS VINICIUS DE SOUZA MORAIS",
        nomeTLC: "MARCUS",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 260,
        nome: "PABLO DIAS MARIANO",
        nomeTLC: "PABLO",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 261,
        nome: "ROBERTO FRANCA ARAUJO",
        nomeTLC: "ROBERTO",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 23,
        nome: "SARA GONÇALVES PINHEIRO",
        nomeTLC: "SARA",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 248,
        nome: "SAULO MATHEUS ARAUJO DE SANTANA",
        nomeTLC: "SAULO MATHEUS",
        diasViagem: [],
        contagem: 0,
        tarefas: 0
    },
    {
        id: 206,
        nome: "THALYSON KELSON LIMA TORRES",
        nomeTLC: "THALYSON",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 229,
        nome: "YAN THADEU PORTO DE OLIVEIRA SANTOS",
        nomeTLC: "YAN",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
]
const TRABALHISTA = [
    {
        id: 108,
        nome: "FELIPE PANTA CARDOSO",
        nomeTLC: "FELIPE",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 158,
        nome: "FERNANDO HENRIQUE BARBOZA NASCIMENTO",
        nomeTLC: "FERNANDO",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 104,
        nome: "GLENISSON NASCIMENTO",
        nomeTLC: "GLENISSON",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 175,
        nome: "MATHEUS CORREIA SANTOS",
        nomeTLC: "MATHEUS CORREIA",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
]
const CIVEL = [
    {
        id: 166,
        nome: "ALÃ FEITOSA CARVALHO",
        nomeTLC: "ALÃ",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 210,
        nome: "EFRAIM SILVA CORREA DOS SANTOS",
        nomeTLC: "EFRAIM",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 187,
        nome: "GABRIEL DAVILA FILGUEIRAS MELLONE",
        nomeTLC: "GABRIEL",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 164,
        nome: "MATHEUS MATOS BARRETO",
        nomeTLC: "MATHEUS MATOS",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 55,
        nome: "RODRIGO AGUIAR SANTOS",
        nomeTLC: "RODRIGO",
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
]
const CALCULO = [
    {
        id: 180,
        nome: "ANSELMO DAVID DOS SANTOS RODRIGUES",
        nomeTLC: "ANSELMO",
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 237,
        nome: "CARLOS EDUARDO DOS SANTOS",
        nomeTLC: "CARLOS",
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 100,
        nome: "GUILHERME JASMIM",
        nomeTLC: "GUILHERME",
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 147,
        nome: "WILKE RODRIGUES DE JESUS",
        nomeTLC: "WILKE",
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0
    },
],
CRM = [
    {
        id: 242,
        nome: "BRYAN CAMPOS DE ANDRADE",
        nomeTLC: "BRYAN",
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 62,
        nome: "HENYR GOIS DOS SANTOS",
        nomeTLC: "HENYR",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 196,
        nome: "KAUÃ DE CARVALHO NASCIMENTO",
        nomeTLC: "KAUÃ",
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 140,
        nome: "LAYNE DA SILVA GOIS",
        nomeTLC: "LAYNE",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
    {
        id: 64,
        nome: "LEANDRO SANTOS",
        nomeTLC: "LEANDRO",
        assignments: [],
        diasViagem: [],
        contagem: 0,
        atrasadas: 0
    },
    {
        id: 193,
        nome: "LINIKER BERNARDO SOARES",
        nomeTLC: "LINIKER",
        interiores: [],
        assignments: [],
        diasViagem: null,
        contagem: 0,
        atrasadas: 0,
        tarefasIntimacoes: 0,
    },
]